# Generated by Django 4.1.2 on 2022-12-04 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('inventory', models.IntegerField()),
                ('brand', models.CharField(max_length=1000)),
                ('model', models.CharField(max_length=1000)),
                ('condition', models.CharField(max_length=1000)),
                ('second_condition', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=1000)),
                ('internal_storage', models.CharField(max_length=1000)),
                ('card_slot', models.CharField(max_length=1000)),
                ('main_camera', models.CharField(blank=True, max_length=1000)),
                ('selfie_camera', models.CharField(blank=True, max_length=1000)),
                ('operating_system', models.CharField(blank=True, max_length=1000)),
                ('color', models.CharField(max_length=1000)),
                ('battery_life', models.CharField(max_length=1000)),
                ('screen_size', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=1000)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('caption', models.CharField(blank=True, max_length=1000)),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.phone')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='main.seller'),
        ),
    ]
