# Generated by Django 4.1.2 on 2022-12-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_category_customer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
