# Generated by Django 4.1.2 on 2022-12-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
    ]
