# Generated by Django 4.1.2 on 2022-12-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_user_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
    ]
