# Generated by Django 4.1.2 on 2022-12-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_in_cart',
            field=models.IntegerField(default=0),
        ),
    ]
