# Generated by Django 4.1.2 on 2022-12-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_customer_password_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='alt_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
